[tool.pytest.ini_options]
markers = [
    "unit: Unit tests",
    "integration: Integration tests", 
    "api: API tests",
    "slow: Slow running tests",
    "smoke: Smoke tests",
    "regression: Regression tests"
]

testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

addopts = [
    "-v",
    "--tb=short", 
    "--disable-warnings",
    "-W", "ignore::pytest.PytestUnknownMarkWarning"
] 
